// lib/cityData.ts
// Unique 11+ context per city — used to differentiate tutor city pages.
// Entries distinguish school-specific admissions and entry stages.
// grammarSchools is a legacy field name; lists may include clearly labelled independent schools.
// Factual repair reviewed 7 October 2026; future-cycle formats require school confirmation.

export interface CityData {
  examBoard: string;
  countyContext: string;
  intro: string;
  grammarSchools: string[];
  prepTip: string;
  nearbyAreas: string[];
}

export const CITY_DATA: Record<string, CityData> = {
  birmingham: {
    examBoard: "West Midlands shared test: check current guidance",
    countyContext: 'Birmingham and the West Midlands',
    intro: "Birmingham grammar-school applications require attention to the shared entrance-test arrangements and each school’s admissions criteria. A qualifying score alone does not guarantee a place.",
    grammarSchools: [
      'King Edward VI Handsworth School for Girls',
      'King Edward VI Aston School',
      'King Edward VI Camp Hill School for Boys',
      'King Edward VI Camp Hill School for Girls',
      'King Edward VI Five Ways School',
      'Sutton Coldfield Grammar School for Girls',
    ],
    prepTip: "Use the official West Midlands registration guidance and the target school’s policy for the relevant entry year. Check eligibility, priority criteria and the separate secondary-school application.",    nearbyAreas: [
      'Solihull',
      'Wolverhampton',
      'Walsall',
      'Dudley',
      'Sutton Coldfield',
      'West Bromwich',
      'Coventry',
      'Lichfield',
      'Tamworth',
      'Redditch',
      'Bromsgrove',
      'Kidderminster',
    ],
  },

  bristol: {
    examBoard: "School-specific independent admissions",
    countyContext: 'Bristol and South Gloucestershire',
    intro: "Bristol families considering entrance assessments should distinguish independent-school applications from the council secondary-school application. Bristol Grammar School is an independent school; its name does not make it a state grammar school.",
    grammarSchools: ["Bristol Grammar School (independent)"],
    prepTip: "Ask each school for its current entry-year assessment information. Bristol Grammar School publishes its own assessment arrangements; do not assume a city-wide GL test.",    nearbyAreas: [
      'Bath',
      'Clevedon',
      'Weston-super-Mare',
      'Thornbury',
      'Keynsham',
      'Portishead',
      'Nailsea',
      'Filton',
      'Kingswood',
      'Yate',
      'Chipping Sodbury',
      'Mangotsfield',
    ],
  },

  cardiff: {
    examBoard: "School-specific independent admissions",
    countyContext: 'Cardiff and South Wales',
    intro: "Cardiff secondary admissions and independent-school entrance assessments are different processes. Howell’s School, Llandaff offers a Year 7 admissions route. Welsh-medium education should not be described as a selective 11+ system.",
    grammarSchools: ["Howell’s School, Llandaff (independent)"],
    prepTip: "Confirm the assessment date and intended entry year with the school. Do not use sixth-form admissions criteria to plan preparation for an 11-year-old.",    nearbyAreas: [
      'Newport',
      'Penarth',
      'Barry',
      'Pontypridd',
      'Caerphilly',
      'Bridgend',
      'Vale of Glamorgan',
      'Rhondda',
      'Llantrisant',
      'Cowbridge',
      'Dinas Powys',
      'Whitchurch',
    ],
  },

  coventry: {
    examBoard: "Warwickshire / West Midlands test: check current guidance",
    countyContext: 'Coventry and Warwickshire',
    intro: "Families in Coventry considering Warwickshire grammar schools should check each school’s priority criteria as well as the shared entrance-test registration. Warwickshire includes selective places at the bilateral Ashlawn School.",
    grammarSchools: [
      'Lawrence Sheriff School (Rugby)',
      'Rugby High School for Girls',
      'Ashlawn School (selective places)',
      'Alcester Grammar School',
    ],
    prepTip: "Check the official Warwickshire guidance for test registration and submit the separate school application through your home local authority. Do not assume living outside Warwickshire prevents test registration.",    nearbyAreas: [
      'Leamington Spa',
      'Rugby',
      'Kenilworth',
      'Nuneaton',
      'Bedworth',
      'Solihull',
      'Warwick',
      'Stratford-upon-Avon',
      'Binley',
      'Baginton',
      'Meriden',
      'Exhall',
    ],
  },

  derby: {
    examBoard: "School-specific independent admissions",
    countyContext: 'Derby and Derbyshire',
    intro: "For Derby families exploring independent-school entry, Derby Grammar School has its own admissions process. Avoid choosing practice materials on the assumption that Derby has a shared GL grammar-school test.",
    grammarSchools: ["Derby Grammar School (independent)"],
    prepTip: "Ask admissions for the correct year-group assessment and any familiarisation material before selecting practice papers.",    nearbyAreas: [
      'Nottingham',
      'Burton upon Trent',
      'Belper',
      'Ilkeston',
      'Long Eaton',
      'Ripley',
      'Matlock',
      'Swadlincote',
      'Uttoxeter',
      'Ashbourne',
      'Heanor',
      'Alfreton',
    ],
  },

  edinburgh: {
    examBoard: "School-specific Scottish admissions",
    countyContext: 'Edinburgh and the Lothians',
    intro: "Edinburgh independent-school applications use Scottish year groups and school-specific assessments. George Watson’s College lists Primary 6, Primary 7 and Senior 1 among its entry points, so confirm the appropriate stage rather than assuming an English Year 7 route.",
    grammarSchools: ["George Watson’s College (independent)"],
    prepTip: "Check the school’s guidance for your child’s age and stage. George Watson’s describes its assessments as age-appropriate and based on education to date, rather than a common English 11+ paper.",    nearbyAreas: [
      'Leith',
      'Musselburgh',
      'Dalkeith',
      'Penicuik',
      'Linlithgow',
      'South Queensferry',
      'Livingston',
      'Bonnyrigg',
      'Portobello',
      'Corstorphine',
      'Morningside',
      'Stockbridge',
    ],
  },

  glasgow: {
    examBoard: "School-specific Scottish admissions",
    countyContext: 'Glasgow and the West of Scotland',
    intro: "Glasgow independent-school admissions should be planned around the Scottish year group and the individual school’s requirements. Hutchesons’ Grammar School is an independent school, and its assessments vary by entry stage.",
    grammarSchools: ["Hutchesons’ Grammar School (independent)"],
    prepTip: "Hutchesons’ states that extensive preparation is not expected. Follow its current assessment guidance instead of assuming a fixed maths, English and verbal-reasoning paper.",    nearbyAreas: [
      'Paisley',
      'Hamilton',
      'Motherwell',
      'East Kilbride',
      'Clydebank',
      'Rutherglen',
      'Cambuslang',
      'Bearsden',
      'Milngavie',
      'Newton Mearns',
      'Bishopbriggs',
      'Kirkintilloch',
    ],
  },

  leeds: {
    examBoard: "School-specific independent admissions",
    countyContext: 'Leeds and West Yorkshire',
    intro: "The Grammar School at Leeds is an independent school. Families should establish the admissions route of each target school rather than assume that a school with “grammar” in its name uses a shared state-school 11+ test.",
    grammarSchools: ["The Grammar School at Leeds (independent)"],
    prepTip: "Check entry requirements and fees or bursary arrangements directly with the school. A practice percentage is not an admission guarantee.",    nearbyAreas: [
      'Bradford',
      'Harrogate',
      'Wakefield',
      'Halifax',
      'Huddersfield',
      'Ilkley',
      'Otley',
      'Morley',
      'Pudsey',
      'Garforth',
      'Wetherby',
      'Dewsbury',
    ],
  },

  leicester: {
    examBoard: "School-specific independent admissions",
    countyContext: 'Leicester and Leicestershire',
    intro: "Leicester Grammar School offers an independent-school Year 7 entry route. Its admissions arrangements should not be applied to other Leicester or Leicestershire secondary schools.",
    grammarSchools: ["Leicester Grammar School (independent)"],
    prepTip: "Use the school’s assessment information for the correct entry year. Separate Year 7 requirements from sixth-form entry and do not assume one county-wide test.",    nearbyAreas: [
      'Loughborough',
      'Hinckley',
      'Coalville',
      'Melton Mowbray',
      'Market Harborough',
      'Oadby',
      'Wigston',
      'Blaby',
      'Syston',
      'Thurmaston',
      'Birstall',
      'Broughton Astley',
    ],
  },

  liverpool: {
    examBoard: "School-specific tests",
    countyContext: 'Liverpool and Merseyside',
    intro: "Liverpool and Wirral offer different school admissions routes, including state selective schools and independent schools. Do not assume that one test or registration covers every school in Merseyside.",
    grammarSchools: [
      'Calday Grange Grammar School',
      'West Kirby Grammar School for Girls',
      'Upton Hall School FCJ',
      'Birkenhead School (independent)',
      'Liverpool Blue Coat School',
      'Merchant Taylors\' School Crosby',
    ],
    prepTip: "Check which schools share a test, and which need separate registration. Use the current school policy rather than a regional assumption about papers or interviews.",    nearbyAreas: [
      'Wirral',
      'St Helens',
      'Warrington',
      'Southport',
      'Bootle',
      'Birkenhead',
      'Wallasey',
      'Crosby',
      'Prescot',
      'Runcorn',
      'Widnes',
      'Newton-le-Willows',
    ],
  },

  london: {
    examBoard: "School-specific tests",
    countyContext: 'London and the Home Counties',
    intro: "London entrance assessments vary by school, consortium and stage. A borough or a provider name alone does not tell you which subjects your child will sit. Grammar-school and independent-school applications also follow different processes.",
    grammarSchools: [
      'Queen Elizabeth\'s School Barnet',
      'The Henrietta Barnett School',
      'Latymer School Edmonton',
      'Tiffin School',
      'Tiffin Girls\' School',
      'Nonsuch High School for Girls',
      'Wallington High School for Girls',
      'Wilson\'s School',
      'St Olave\'s Grammar School',
    ],
    prepTip: "List the subjects and stages for each target school from its official admissions policy. Keep test registration, any second-stage assessment and the school application deadline separate.",    nearbyAreas: [
      'Barnet',
      'Sutton',
      'Kingston upon Thames',
      'Bromley',
      'Enfield',
      'Harrow',
      'Richmond',
      'Croydon',
      'Redbridge',
      'Waltham Forest',
      'Bexley',
      'Merton',
    ],
  },

  manchester: {
    examBoard: "School-specific: confirm provider and cycle",
    countyContext: 'Greater Manchester and Cheshire',
    intro: "Greater Manchester families may consider the Trafford grammar schools, but consortium membership and individual school arrangements matter. Do not rely on older references to CEM when choosing preparation for a 2027 exam.",
    grammarSchools: [
      'Altrincham Grammar School for Boys',
      'Altrincham Grammar School for Girls',
      'Sale Grammar School',
      'Stretford Grammar School',
      'Urmston Grammar School',
      'Loreto Grammar School',
    ],
    prepTip: "Read the current Trafford consortium announcement and each target school’s policy for the intended entry year before buying provider-specific papers. Other Trafford schools may have separate arrangements.",    nearbyAreas: [
      'Salford',
      'Stockport',
      'Oldham',
      'Rochdale',
      'Bury',
      'Bolton',
      'Wigan',
      'Altrincham',
      'Sale',
      'Didsbury',
      'Stretford',
      'Cheadle',
    ],
  },

  newcastle: {
    examBoard: "School-specific independent admissions",
    countyContext: 'Newcastle and the North East',
    intro: "Royal Grammar School Newcastle is an independent school with its own senior-school admissions process. Families should check target schools individually rather than assume a shared North East grammar-school exam.",
    grammarSchools: ["Royal Grammar School Newcastle (independent)"],
    prepTip: "Confirm the school’s current assessment and application requirements, including which entry year the published dates cover.",    nearbyAreas: [
      'Gateshead',
      'Sunderland',
      'Durham',
      'South Shields',
      'North Shields',
      'Hexham',
      'Morpeth',
      'Whitley Bay',
      'Cramlington',
      'Chester-le-Street',
      'Stanley',
      'Consett',
    ],
  },

  nottingham: {
    examBoard: "School-specific independent admissions",
    countyContext: 'Nottingham and Nottinghamshire',
    intro: "Nottingham High School is an independent school. Families considering its entrance process should use school-specific guidance rather than assume a common Nottinghamshire 11+ examination.",
    grammarSchools: ["Nottingham High School (independent)"],
    prepTip: "Request current assessment guidance from the school; sixth-form academic requirements are not Year 7 entrance requirements.",    nearbyAreas: [
      'Derby',
      'Leicester',
      'Mansfield',
      'Newark',
      'Beeston',
      'Arnold',
      'Carlton',
      'Long Eaton',
      'Ilkeston',
      'Hucknall',
      'Bulwell',
      'West Bridgford',
      'Eastwood',
      'Worksop',
      'Grantham',
      'Stapleford',
    ],
  },

  oxford: {
    examBoard: "School-specific independent admissions",
    countyContext: 'Oxford and Oxfordshire',
    intro: "Oxford High School offers an independent-school senior admissions route. Its assessment process should not be presented as an Oxfordshire-wide state grammar-school test.",
    grammarSchools: ["Oxford High School (independent)"],
    prepTip: "Check the entry year, assessment day and bursary deadlines separately. Select preparation only after confirming the school’s current requirements.",    nearbyAreas: [
      'Abingdon',
      'Witney',
      'Didcot',
      'Banbury',
      'Bicester',
      'Henley-on-Thames',
      'Wallingford',
      'Thame',
      'Faringdon',
      'Wantage',
      'Chipping Norton',
      'Woodstock',
    ],
  },

  reading: {
    examBoard: "School-specific: confirm provider and cycle",
    countyContext: 'Reading and Berkshire',
    intro: "Reading School, Kendrick and the Slough grammar schools have distinct admissions arrangements. Reading School’s published information for September 2027 entry identifies FSCE; it should not be described as part of a single Berkshire GL test.",
    grammarSchools: [
      'Reading School',
      'Kendrick School',
      'Upton Court Grammar School',
      'Herschel Grammar School',
      'Langley Grammar School',
      'St Bernard\'s Catholic Grammar School',
    ],
    prepTip: "For an exam taken in 2027, find the policy for the intended school-entry year. Published 2026 test dates for September 2027 entry must not be rolled forward. Check each school’s registration separately.",    nearbyAreas: [
      'Slough',
      'Windsor',
      'Maidenhead',
      'Wokingham',
      'Bracknell',
      'Henley-on-Thames',
      'Newbury',
      'Marlow',
      'Caversham',
      'Tilehurst',
      'Earley',
      'Woodley',
    ],
  },

  sheffield: {
    examBoard: "School-specific independent admissions",
    countyContext: 'Sheffield and South Yorkshire',
    intro: "Sheffield Girls’ offers independent senior-school admissions. Families should distinguish school-specific entrance assessments from the local authority secondary-school application process.",
    grammarSchools: ["Sheffield Girls’ (independent)"],
    prepTip: "Use the target school’s current senior admissions guidance rather than assuming a shared Sheffield GL test.",    nearbyAreas: [
      'Rotherham',
      'Doncaster',
      'Barnsley',
      'Chesterfield',
      'Worksop',
      'Stocksbridge',
      'Chapeltown',
      'Hillsborough',
      'Ecclesfield',
      'Swallownest',
      'Mosborough',
      'Aughton',
    ],
  },

  southampton: {
    examBoard: "School-specific independent admissions",
    countyContext: 'Southampton and Hampshire',
    intro: "Families considering King Edward VI School in Southampton should follow its independent-school admissions process. Do not assume that Hampshire has a shared county-wide 11+ registration system.",
    grammarSchools: ["King Edward VI School Southampton (independent)"],
    prepTip: "Contact the school about the appropriate entry route and year. Sixth-form colleges and other secondary schools should not be listed as equivalent 11+ options.",    nearbyAreas: [
      'Portsmouth',
      'Winchester',
      'Eastleigh',
      'Fareham',
      'Chandlers Ford',
      'Romsey',
      'Totton',
      'Hedge End',
      'Bishopstoke',
      'Fair Oak',
      'Bursledon',
      'Netley',
    ],
  },

  brighton: {
    examBoard: "School-specific independent admissions",
    countyContext: 'Brighton and East Sussex',
    intro: "Brighton College offers 11+ entry into its Lower School. Families should check each independent school’s admissions route rather than assume a common Brighton or East Sussex grammar-school test.",
    grammarSchools: ["Brighton College (independent)"],
    prepTip: "Confirm the correct entry point: Brighton College distinguishes 11+ Lower School entry from its Prep School. Check availability and application dates directly.",    nearbyAreas: [
      'Hove',
      'Worthing',
      'Lewes',
      'Eastbourne',
      'Haywards Heath',
      'Burgess Hill',
      'Shoreham-by-Sea',
      'Portslade',
      'Newhaven',
      'Seaford',
      'Peacehaven',
      'Lancing',
    ],
  },

  bradford: {
    examBoard: "School-specific independent admissions",
    countyContext: 'Bradford and West Yorkshire',
    intro: "Bradford Grammar School is independent and lists Year 7 as a main entry point. A school’s historical name does not establish whether it selects pupils through an 11+ test.",
    grammarSchools: ["Bradford Grammar School (independent)"],
    prepTip: "Check the individual school’s current admissions process and familiarisation information. Do not assume all schools around Bradford use the same provider.",    nearbyAreas: [
      'Leeds',
      'Halifax',
      'Bingley',
      'Shipley',
      'Keighley',
      'Ilkley',
      'Baildon',
      'Pudsey',
      'Guiseley',
      'Yeadon',
      'Morley',
      'Dewsbury',
    ],
  },
};

/**
 * Returns city data for a given city slug, or a sensible generic fallback.
 */
export function getCityData(slug: string): CityData {
  return CITY_DATA[slug] ?? {
    examBoard: 'Confirm with the target school',
    countyContext: slug.charAt(0).toUpperCase() + slug.slice(1),
    intro: `Families in and around ${slug.charAt(0).toUpperCase() + slug.slice(1)} should confirm each target school’s admissions route, entry year and assessment requirements before choosing preparation materials.`,
    grammarSchools: [],
    prepTip: 'Use current official admissions guidance and age-appropriate practice. Confirm the exam year separately from the school-entry year.',
    nearbyAreas: [],
  };
}
